name: DramaticTP
main: com.mike724.dramatictp.DramaticTP
author: Mike724
version: ${version}
commands:
    dramatictp:
        description: Manage DramaticTP
        aliases: [dtp,dt]
        usage: /<command> help